FROM golang:alpine as builder

WORKDIR /app

RUN go mod init app/fullcycle

COPY /app ./

RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go-docker-challenge

FROM scratch

COPY --from=builder /go-docker-challenge .

CMD [ "/go-docker-challenge" ]